### ISSUE TITLE
US41 - Filtragem de ajudas

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#121]
### Descrição:
Eu, como usuário, desejo poder filtrar as ofertas de ajuda entre as categorias para melhor identificar qual a oferta que me ajuda.

### Critérios de aceitação:

- A filtragem é feita corretamente de acordo com a categoria selecionada.
- Deverá ser feita a filtragem de acordo com a categoria, independentemente se a oferta / pedido tiver mais de uma categoria.
- Foi implementado a lógica de filtragem tanto nos pedidos criados, como nas ofertas criadas.

### Tarefas:

- [ ] Criar filtragem para ofertas e pedidos de ajuda que suportam mais de uma categoria.
- [ ] Implementar filtragem no front-end (apenas nas listas de pedidos).
- [ ] Testar se a filtragem ocorre independente da quantidade de categorias de determinado pedido.

**Comment by AnaCarolcs** [comment]
@juniopereirab essa issue já foi feita?

**Comment by juniopereirab** [comment]
> @juniopereirab essa issue já foi feita?

Sim
