### ISSUE TITLE
US44 - Listagem de pessoas interessadas

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#124]
### Descrição:
Eu, como usuário, gostaria de ver as pessoas interessadas na minha oferta de ajuda para que eu possa escolher as que desejo ajudar.

### Critérios de aceitação:

- Listagem de todas as pessoas interessadas na minha oferta foi feita corretamente
- A listagem está seguindo os padrões de usabilidade do aplicativo

### Tarefas:

- [ ] Listar pessoas interessadas na oferta criada.
- [ ] Fazer pessoas aparecem de acordo com os padrões, com informações como Nome, Cidade.
- [ ] Testar a funcionalidade

### Observações:

- Os padrões de usabilidade vão estar disponíveis em breve. Será anexado à essa issue.

**Comment by AnaCarolcs** [comment]
Essa issue estava na R2, mas retiramos na repriorização.

**Comment by devsalula** [comment]
Manter para a V2. Essa issue trava a #125

**Comment by RcleydsonR** [comment]
O back-end dessa issue já estava praticamente todo composto, o único problema que estava dando é que nas agregações do helpOfferRepository não estava retornando os arrays das possíveis pessoas ajudadas e entidades também. Foi feita apenas uma reformulação nessa agregação para atender os requisitos dessa issue.
