### ISSUE TITLE
US45 - Aceitação de pessoas interessadas para ajudar

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#125]
### Descrição:
Eu, como usuário que cria a oferta, gostaria de aceitar uma ou mais pessoas para poder ajudar.

### Critérios de aceitação:

- Foi possível escolher uma ou mais pessoas para que eu possa ajudar
- As informações do usuário que criou a ajuda foi passada corretamente para os interessados e vice-versa.
- Forma de aceitação está de acordo com os padrões de usabilidade.
- Foi configurada a notificação para o usuário aceito na oferta.

### Tarefas:

- [x] Tornar possível a escolha de uma ou mais pessoas que possam ser ajudadas.
- [x] Passar as informações necessárias entre os usuários corretamente.
- [x] Configurar notificações
- [x] Testar funcionalidade.

### Observações:

- Os padrões de usabilidade vão estar disponíveis em breve. Será anexado à essa issue.

**Comment by AnaCarolcs** [comment]
Depende da issue #124

**Comment by AnaCarolcs** [comment]
Essa issue estava na R2, mas retiramos na repriorização.

**Comment by devsalula** [comment]
Manter para a V2. Porém deve resolver a issue #124
