### ISSUE TITLE
US46 - Escolher oferta de ajuda

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#126]
### Descrição:
Eu, como usuário interessado em uma oferta de ajuda, gostaria de escolher uma oferta de ajuda.

### Critérios de aceitação:

- Foi possível se candidatar a receber ajuda de uma oferta.
- As notificações foram entregues corretamente para o autor da oferta.

### Tarefas:

- [x] Implementar a forma de escolha do usuário por uma oferta, e assim que o usuário escolher sua oferta o mesmo ir para a lista de interessados.
- [x] Configurar as notificações para o autor da oferta.
- [ ] Testar funcionalidade em ambos os pares de usuários.

### Observações:

- É recomendado que essa issue se resolva com #125

**Comment by AnaCarolcs** [comment]
Falta testar

**Comment by AnaCarolcs** [comment]
Essa issue estava na R2, mas retiramos na repriorização.

**Comment by devsalula** [comment]
O @darmsDD já fez essa feature.
