### ISSUE TITLE
US47 - Notificações para ofertas

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#127]
### Descrição:
Eu, como usuário que cria uma ajuda, gostaria de receber uma notificação quando alguém se interessar pela minha oferta de ajuda para melhor gerenciar as pessoas que irei ajudar.

### Critérios de aceitação:

- Notificações estão sendo enviadas corretamente.

### Tarefas:

- [ ] Verificar configurações das notificações.
- [ ] Testar funcionalidade.

### Observações:

- Essa história é baseada em uma verificação com as histórias #125 e #126 . É recomendado que os times responsáveis pelo seu desenvolvimento trabalhem juntos.

**Comment by AnaCarolcs** [comment]
@WelisonR e @darmsDD vocês estão com essa tarefa, certo? Há alguma atualização?

**Comment by darmsDD** [comment]
Sim, tivemos dificuldades essa semana, mas estamos progredindo.

**Comment by AnaCarolcs** [comment]
Essa issue estava na R2, mas retiramos na repriorização.

**Comment by devsalula** [comment]
@darmsDD meio brabo, é brabo por ter feito a issue. Mas é meio por não ter fechado a issue. 😂
