### ISSUE TITLE
US53 - Finalizar campanha a qualquer momento

### ISSUE THREAD

**Issue by sudjoao** [mia-ajuda/Documentation#133]
### Descrição:

Eu, como um usuário ong, gostaria de poder finalizar minha campanha a qualquer momento, independente de prazo. 

### Critérios de aceitação:

- ONG poder finalizar campanha a todo momento;
- Campanha sumir do mapa após finalizada.

### Tarefas:

- [ ] Botão para ONG finalizar a campanha;
- [x] Campanha sumir do mapa;
- [ ] Campanha não aparecer em campanhas ativas.

### Observações:

- Depende da issue US51 - Cadastrar Campanhas [#131]

**Comment by AnaCarolcs** [comment]
@sudjoao essa tarefa está com você?

**Comment by sudjoao** [comment]
> @sudjoao essa tarefa está com você?

Não está comigo, porém lá no backlog também está falando que já foi realizada.
