### ISSUE TITLE
US55 - Receber ajuda de diferentes usuários

### ISSUE THREAD

**Issue by sudjoao** [mia-ajuda/Documentation#135]
### Descrição:

Eu, como uma ONG, gostaria de poder receber várias ajudas de diferentes usuários sem precisar recriar uma mesma campanha. 

### Critérios de aceitação:

- Campanha não finalizar quando alguém oferecer ajuda;
- Campanha poder ter vários ajudantes.

### Tarefas:

- [ ] Deixar campanha ativa mesmo após receber ajuda.

### Observações:

Depende da issue US48 Criação de ONGS e Instituições [#128]

**Comment by AnaCarolcs** [comment]
@sudjoao como foi você que criou essa issue, ela ainda faz sentido para o projeto?

**Comment by sudjoao** [comment]
Sim, porém, acabei de dar uma olhada no backlog do projeto e ela está contando como feita, então pode ser fechada. 

> @sudjoao como foi você que criou essa issue, ela ainda faz sentido para o projeto?
