### ISSUE TITLE
US57 - Finalizar campanha

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#137]
### Descrição:
Eu, como uma ONG, gostaria de poder finalizar uma campanha a qualquer momento sem depender que a pessoa que ajudou finalize também. 

### Critérios de aceitação:

- O perfil de ONG e Instituição conseguem finalizar uma campanha independentemente da aprovação ou finalização de outros.
- O status de finalizado foi implementado corretamente.
- Para os participantes daquela campanha é enviado uma notificação informando o fim da campanha.

### Tarefas:

- [ ] Implementar o status de campanha no back-end
- [ ] Implementar a possibilidade de finalizar um campanha através do aplicativo.
- [ ] Configurar notificação sobre o fim da campanha para os participantes.

**Comment by AnaCarolcs** [comment]
@juniopereirab qual a atualização da issue?

**Comment by AnaCarolcs** [comment]
@DanilloGS essa issue foi finalizada? 
![Captura de Tela 2021-06-02 às 16 17 16](https://user-images.githubusercontent.com/9967427/120539481-0204be80-c3be-11eb-90cf-4b024a23e791.png)

**Comment by devsalula** [comment]
Já foi realizado. Como @DanilloGS tá como assigne, com certeza feito. Né não @DanilloGS ?
