### ISSUE TITLE
US59 - Listagem de campanhas

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#139]
### Descrição:
Eu, como uma ONG, gostaria de acessar minha página de campanhas para visualizar as campanhas que eu criei.

### Critérios de aceitação:

- Foi feita a listagem de todas as campanhas criadas pela ONG.
- A lista de campanhas é ordenada em ordem de mais recente para menos recente.
- As informações de cada campanha foram exibidas corretamente de acordo com os padrões de desenvolvimento.

### Tarefas:

- [x] Fazer a requisição de listagem corretamente do banco de dados para o front-end
- [x] Fazer as campanhas aparecerem de acordo com os padrões, informações como Nome, Descrição e Cidade.
- [x] Testar funcionalidade

### Observações:

- Os padrões de usabilidade vão estar disponíveis em breve. Será anexado à essa issue.

**Comment by AnaCarolcs** [comment]
@PedroLimass essa issue foi finalizada?
