### ISSUE TITLE
US60 - Notificar interesse por campanhas

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#140]
### Descrição:
Eu, como uma ONG, gostaria de poder receber notificações quando alguém se interessar em participar de uma campanha

### Critérios de aceitação:

- As notificações estão sendo recebidas corretamente.
- A funcionalidade foi testada.

### Tarefas:

- [ ] Configurar notificações para ONGs receberem no momento em que receberem uma requisição.
- [ ] Testar funcionalidade.

**Comment by AnaCarolcs** [comment]
@juniopereirab essa issue ainda faz sentido para o projeto?
