### ISSUE TITLE
M01 - Campo inválido de email após preenchimento automático.

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#141]
### Descrição
Melhorar o tratamento de campo inválido para o email, que é identificado como invalido caso o usuário utilize o preenchimento automático de email do celular.

**Comment by AnaCarolcs** [comment]
@juniopereirab ainda vamos aplicar essa melhoria?

**Comment by juniopereirab** [comment]
> @juniopereirab ainda vamos aplicar essa melhoria?

É necessário ver se ainda existe o problema dentro do app. Em caso positivo, devemos sim aplicar essa melhoria.

**Comment by devsalula** [comment]
@juniopereirab sabe me informar se esse problema acontece apenas na tela de login?

**Comment by juniopereirab** [comment]
> @juniopereirab sabe me informar se esse problema acontece apenas na tela de login?

Esse bug acontece durante o cadastro.

**Comment by AnaCarolcs** [comment]
Foi reportado numa daily que essa issue já havia sido concluída.
![Captura de Tela 2021-06-02 às 16 17 53](https://user-images.githubusercontent.com/9967427/120539588-1943ac00-c3be-11eb-894d-d290d686e67d.png)
