### ISSUE TITLE
M10 - Teclado sobrepondo botão de "Preciso de ajuda"

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#150]
### Descrição:
Na tela de Criar Ajuda, o botão de "Preciso de ajuda" e o contador de caracteres da descrição, são sobrepostos pelo teclado.

**Comment by sudjoao** [comment]
[Pull request](https://github.com/mia-ajuda/Frontend/pull/92) já foi aceito, vou fechar a issue aqui.

**Comment by AnaCarolcs** [comment]
@sudjoao , você reabriu essa issue. Qual a atualização? Foi feita?

**Comment by sudjoao** [comment]
Fala @AnaCarolcs , então, eu reabri essa issue pois ela não foi resolvida, porque o componente do próprio react native estava com bug na versão daquela época, pois a propriedade não estava funcionando como devia, posso checkar essa semana se teve alguma atualização do componente para essa issue ser realizada.
