### ISSUE TITLE
M12 - Título não apresentado corretamente

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#152]
### Descrição:
Ao clicar em uma ajuda, o título dependendo do tamanho não aparece por completo, e não aparece também acima da descrição. Tornando-se impossível de ver o que o usuário precisa de fato, caso ele não escreva na descrição.

**Comment by sudjoao** [comment]
[Pull request](https://github.com/mia-ajuda/Frontend/pull/92) já foi aceito, vou fechar a issue aqui.
