### ISSUE TITLE
M13 - Ofertas ou pedidos pendentes

### ISSUE THREAD

**Issue by juniopereirab** [mia-ajuda/Documentation#153]
### Descrição:
Melhorar a forma como o usuário pode identificar que a oferta foi feita com sucesso à algum pedido, pois não aparece como "pendente" deixando a entender que ele não efetuou a oferta, fazendo com que ele faça várias ofertas em um mesmo pedido.

**Comment by sudjoao** [comment]
Boa tarde, @juniopereirab , queria saber quais são as alternativas que você vê para melhorar esta tela, porque eu estava observando e vi que já existem alguns pontos, e até mesmo mensagens falando sobre a oferta de sido feita com sucesso, como pode ser observado a baixo, se você puder explicar melhor quais possíveis coisas podem melhorar seria muito top.

![Captura de tela de 2020-08-10 13-24-18](https://user-images.githubusercontent.com/46005310/89817304-516fba80-db1e-11ea-9449-065134670990.png)
![Captura de tela de 2020-08-10 13-24-34](https://user-images.githubusercontent.com/46005310/89817306-52a0e780-db1e-11ea-8830-cd2af891d482.png)
![Captura de tela de 2020-08-10 13-24-43](https://user-images.githubusercontent.com/46005310/89817308-52a0e780-db1e-11ea-9dec-bb15f812584e.png)

**Comment by juniopereirab** [comment]
Como agora tudo vai estar disposto em uma página de histórico, seria interessante ver a possibilidade de adicionar um status de "pendente" ou algo do tipo. O motivo é para que o usuário pudesse ver os pedidos que ele fez a oferta mas que ainda não foi aceita. Então por exemplo, quando eu fizesse uma oferta para um pedido existente, ou um pedido para uma oferta existente no mapa. Esse pedido fosse para o meu histórico como "pendente". Seria interessante fazer isso no prototipo primeiro, a página de historico está assim agora.
![image](https://user-images.githubusercontent.com/17153869/89840652-28175480-db47-11ea-8b0a-89a67d04bab1.png)

No canto inferior direito de cada card, colocar um nomezinho "pendente" pra indicar ao usuário. "andamento" para pedidos aceitos, vou levar isso pra daily. E já passo o que foi decidido.

**Comment by juniopereirab** [comment]
Agora que eu vi que a label vermelha aparece o status do pedido, seria nesse nível, mas aparecendo "pendente" quando o pedido não foi aceito ainda por ninguém.

**Comment by AnaCarolcs** [comment]
@juniopereirab e @sudjoao o que ficou decidido?

**Comment by juniopereirab** [comment]
> @juniopereirab e @sudjoao o que ficou decidido?

Nós decidimos dividir as telas entre Meus Pedidos, Minhas Ofertas e Histórico. Sendo assim a divisão fez com que essa issue para o usuário comum não faça mais sentido. Mas ainda sim ela está presente no perfil de Organizações. Então é necessário verificar sua finalização.

**Comment by AnaCarolcs** [comment]
@sudjoao , sabe se ela foi finalizada?

**Comment by AnaCarolcs** [comment]
@DanilloGS essa issue foi concluída? 
![Captura de Tela 2021-06-02 às 16 19 00](https://user-images.githubusercontent.com/9967427/120539728-42fcd300-c3be-11eb-8920-75e02ad95000.png)

**Comment by devsalula** [comment]
Já tem como ver no app. Fechei
