### ISSUE TITLE
Refatorar Docker do Backend

### ISSUE THREAD

**Issue by WelisonR** [mia-ajuda/Documentation#159]
### Descrição

Atualmente, o docker voltado para desenvolvimento difere em algumas configurações em relação ao docker que se encontra em produção e, além disso, as configurações do docker de produção não se encontram no repositório do backend. Nesse sentido, há a necessidade de refatorar esse arquivo de modo a assemelhar tais arquivos e melhorar a questão das variáveis de ambiente em produção.

### Critérios de aceitação:

- [ ] Docker para ambiente de desenvolvimento;
- [ ] Docker para ambiente de produção.
- [ ] Verificar solução automatizada para as variáveis de ambiente do docker.

### Tarefas:

- [ ] Docker default para desenvolvimento e produção;
- [ ] Docker com configurações de desenvolvimento;
- [ ] Docker com configurações de produção;
- [ ] Verificar solução automatizada para as variáveis de ambiente do docker.

**Comment by AnaCarolcs** [comment]
@WelisonR houve essa refatoração?

**Comment by WelisonR** [comment]
@AnaCarolcs Não, essa issue está pendente

**Comment by AnaCarolcs** [comment]
@WelisonR resolvemos?

**Comment by WelisonR** [comment]
Não, @AnaCarolcs. Não sei mais a relevância dessa issue na implementação atual do projeto. Acredito que a issue possa ser fechada e, se necessário, reavaliada posteriormente.
