### ISSUE TITLE
Bug ao sair

### ISSUE THREAD

**Issue by darmsDD** [mia-ajuda/Documentation#160]
**Descreva o bug**
Aparece a tela do tutorial ao sair

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/42387797/93540611-9b706b00-f92a-11ea-8e70-ccb25b1c5ef7.gif)
**Comportamento esperado**
Não aparecer a tela do tutorial.

**Comment by AnaCarolcs** [comment]
Issue já resolvida.
