### ISSUE TITLE
Criação de tela individual de Campanha

### ISSUE THREAD

**Issue by sudjoao** [mia-ajuda/Documentation#163]
### Descrição:
Criar tela de listagem individual de campanha.
### Critérios de aceitação:

- Foi feita a tela de informações sobre a campanha.
- As informações de cada campanha foram exibidas corretamente de acordo com os padrões de desenvolvimento.

### Tarefas:
- [ ] Criar rota de campanha individual;
- [ ] Criar tela da campanha;
- [ ] Linkar listagem de campanhas com tela individual da campanha.

**Comment by AnaCarolcs** [comment]
@sudjoao essa issue é uma melhoria ou US?

**Comment by sudjoao** [comment]
@AnaCarolcs é pra ser uma US, porém não tinha sido definida durante o backlog,  vimos que precisava dessa funcionalidade pra R2 para parte das ongs estar funcionando 100%, a issue já da finalizada, agora que vi que não tinha aberto o PR, vou abrir agora

**Comment by AnaCarolcs** [comment]
> @AnaCarolcs é pra ser uma US, porém não tinha sido definida durante o backlog, vimos que precisava dessa funcionalidade pra R2 para parte das ongs estar funcionando 100%, a issue já da finalizada, agora que vi que não tinha aberto o PR, vou abrir agora

Obrigada, @sudjoao !!

**Comment by AnaCarolcs** [comment]
@sudjoao o PR foi aberto e aceito?
