### ISSUE TITLE
Persistência de conta de usuário logado não está funcionando no Expo

### ISSUE THREAD

**Issue by sudjoao** [mia-ajuda/Documentation#164]
**Descreva o bug**
Toda vez que o aplicativo é aberto pelo dispositivo físico ou emulador é necessário logar novamente.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Logar no app;
2. Reabrir o app.

**Comportamento esperado**
Usuário continuar logado.

**Informações adicionais**
Segundo alguns membros do projeto, este bug pode estar ocorrendo pois na nova atualização da react native a biblioteca onde o async storage é importado mudou, então o bug pode ser por conta disso.

**Comment by devsalula** [comment]
@Phe0 manda bala

**Comment by devsalula** [comment]
@Phe0 matou a issue a pau!
Boa!
