### ISSUE TITLE
Erro ao deletar Oferta de ajuda

### ISSUE THREAD

**Issue by devsalula** [mia-ajuda/Documentation#166]
**Descreva o bug**
Ao criar uma conta normal e criar uma oferta de ajuda. Se o usuário precisar deletar a oferta de ajuda ele tomará um erro.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Faça login na aplicação como usuário normal
2. Vá na tela de atividades em "Minhas Ofertas"
3. Delete uma oferta

**Comportamento esperado**
O comportamento esperado era uma deleção de oferta bem sucedida.

**Comment by devsalula** [comment]
@RcleydsonR e @mangabeiras mandem bala!

**Comment by RcleydsonR** [comment]
Me parece que esse bug já foi corrigido, estou recebendo o comportamento esperado ao deletar a campanha.

**Comment by RcleydsonR** [comment]
O bug ainda persistente é o de deletar uma oferta de ajuda.

**Comment by AnaCarolcs** [comment]
@RcleydsonR você ficará responsável por corrigir?

**Comment by RcleydsonR** [comment]
Já estou trabalhando nisso @AnaCarolcs !
