### ISSUE TITLE
Erro na tela de notificações

### ISSUE THREAD

**Issue by devsalula** [mia-ajuda/Documentation#167]
**Descreva o bug**
Ao clicar em uma notificação, um erro é lançado.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para a tela de Notificações
2. Clique em uma Notificação
4. Veja o erro

**Comportamento esperado**
Os detalhes da notificação deveriam ser exibidos.

**Comment by devsalula** [comment]
@DanilloGS e @darmsDD aqui o bug que reportei

**Comment by AnaCarolcs** [comment]
@DanilloGS essa issue tá com você?
