### ISSUE TITLE
Ícone no fundo do card de "Meus Pedidos" saindo do card

### ISSUE THREAD

**Issue by sudjoao** [mia-ajuda/Documentation#169]
**Descreva o bug**
O ícone da casa que fica no fundo dos pedidos está saindo para fora.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Crie 1 pedido de ajuda;
2. Vá na tela de meus pedidos.

**Comportamento esperado**
A imagem estar dentro do card.

**Screenshots ou capturas de tela**
![image](https://user-images.githubusercontent.com/46005310/120803151-a4858480-c519-11eb-9841-eb898c162be0.png)

**Comment by devsalula** [comment]
@DanilloGS corrige para segunda, por favor?

**Comment by devsalula** [comment]
eu assumi a issue.
Tá feito, PR aberto: https://github.com/mia-ajuda/Frontend/pull/154
