### ISSUE TITLE
Bug de zero ajudas no mapa

### ISSUE THREAD

**Issue by devsalula** [mia-ajuda/Documentation#170]
Foi percebido um bug quando o mapa possuía 0 ofertas. Assim é necessário testar se esse bug também ocorre com as ajudas.

**Comment by darmsDD** [comment]
Foi testado este bug e ele não ocorre para as ajudas. Me pareceu que isso ocorre  pois as ajudas usam o reducer com o dispatch para salvar as ajudas.
`dispatch({
                    type: actions.help.storeList,
                    helps: helpListArray,
                });` 
enquanto que as ofertas atualmente usam setState.
 `setHelpOfferList(helpOfferListResponse);`
