### ISSUE TITLE
Bug da organização como possível ajudante

### ISSUE THREAD

**Issue by RcleydsonR** [mia-ajuda/Documentation#172]
**Descreva o bug**
Organizações podem se candidatar como ajudante de um pedido de ajuda de alguma pessoa porém para a pessoa a organização não aparece como possível ajudante (mesmo aparecendo notificação)

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Logue como usuário normal.
2. Crie um pedido de ajuda.
3. Logue como uma organização.
4. Candidate-se como ajudante do pedido de ajuda criado anteriormente.
------ Não era pra haver essa etapa 4.
5. Logue como usuário normal novamente.
6. Receba a notificação do possível ajudante do pedido de ajuda.
7. Entre na descrição do pedido de ajuda e não encontre a organização como possível ajudante.

**Comportamento esperado**
A organização não pode se candidatar como possível ajudante de um pedido de ajuda
OU
A organização aparece na tela de possíveis ajudantes e pode ser selecionada como um

**Comment by devsalula** [comment]
@sudjoao aqui
