### ISSUE TITLE
Spike - Verificar a necessidade da pasta Repository

### ISSUE THREAD

**Issue by darmsDD** [mia-ajuda/Documentation#178]
### Descrição:
Verificar a utilidade da pasta Repository no projeto que é o local onde são feitas as queries ao banco de dados. Maneiras de fazer a query:
- Manter no Repository
- Mudá-las para a Service
- Outra Solução

Pesquisar como essa mudanças pode trazer melhorias e afetar os testes que serão desenvolvidos.

### Critérios de aceitação:

- Encontrar uma solução que traga melhorias na arquitetura
- Funcionalidade testada;

### Tarefas:

- [x] Pesquisar alternativas
- [ ] Explicar a decisão para os demais membros da equipe
- [ ] Aplicar mudanças caso existam
- [ ] Testado

**Comment by thiagohdaqw** [comment]
## Um possivel problema
A repository, atualmente, está muito acoplada e pouco reutilizável, uma vez que, na maioria dos casos, os métodos retornam um instancia de um documento com campos e agregações já predefinidos. Isso se torna um problema na hora que você precisa adicionar um novo serviço com campos diferentes dos já pre-definidos. Atualmente, há dois caminhos: Chamar um método que retorna os atributos que voce quer e mais um monte de "lixo"; Ou adicionar mais um método novo no repository que retorna os atributos que voce precisa.

## Possivel solução - Dependency Injection
Para os casos mais complexos, que exige uma logica de negócio mais especifica, há, realmente, a necessidade de uma repository especifico. No entanto, os atributos e agregações necessitados poderiam ser decididos por quem chama esse método.

**Comment by juniopereirab** [comment]
Como primeiro passo, vai ser utilizar melhor a forma como o Mongoose interage com as models criadas através dele, reduzindo o escopo das Services e removendo os repositories para ficar mais fácil de se manter.

**Comment by juniopereirab** [comment]
Porém, essas mudanças vão ocorrer de forma gradual em acompanhamento com as outras frentes de pesquisa.
