### ISSUE TITLE
Verificação de lentidão em queries ao banco de dados

### ISSUE THREAD

**Issue by darmsDD** [mia-ajuda/Documentation#179]
### Descrição:
Alguns membros do Mia-Ajuda relataram lentidão em realizar queries ao banco de dados. O objetivo é encontrar onde existe
e qual a causa dessas lentidões. 

### Critérios de aceitação:

- Mostrar que a nova solução diminui a lentidão das queries.
- Funcionalidade testada;

### Tarefas:

- [ ] Conversar com os membros que tiveram lentidão para facilitar a descoberta das queries problemas.
- [ ] Investigar se indexação pode ajudar https://docs.mongodb.com/manual/indexes/.
- [ ] Resolver a lentidão ou ao menos diminuí-la
- [ ] Testar

**Comment by devsalula** [comment]
Não foi detectado problema no ambiente no momento que testamos.
A suspeita que temos era que o membro que teve o problema de lentidão foi por conta da sua conexão de internet.
