### ISSUE TITLE
Bug das organizações não aparecerem como possíveis ajudantes de um pedido de ajuda

### ISSUE THREAD

**Issue by RcleydsonR** [mia-ajuda/Documentation#189]
**Descreva o bug**
Quando uma pessoa cria um pedido de ajuda e uma organização se oferece pra ajudar, é recebido a notificação, atualizado o badge de possíveis ajudantes, mas quando aberta a lista não aparece a instituição, provavelmente um problema do back-end não estar retornando as informações das instituições que são possíveis ajudantes.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Tenha uma conta de usuário normal e realize um pedido de ajuda.
2. Uma conta de organização oferece ajuda pro pedido criado anteriormente.
3. Na conta de usuário normal, vá para "Meus pedidos".
4. Clique em "Possíveis ajudantes"
5. Verifique que a organização não está na lista de possíveis ajudantes mesmo ela sendo um.

**Comportamento esperado**
Quando a organização oferecer ajuda, ela deve ser mostrada na lista de possíveis ajudantes para o dono do pedido.

**Screenshots ou capturas de tela**
![image](https://user-images.githubusercontent.com/74625814/127569079-5f0fed85-6e28-4b78-a07a-9a174185fc0a.png) ![image](https://user-images.githubusercontent.com/74625814/127569143-c5573811-1815-4b05-aaa1-93710184aa87.png)![image](https://user-images.githubusercontent.com/74625814/127569216-813d1a74-7f4e-4fa3-95d8-da5c3f1c3767.png)

**Comment by thiagohdaqw** [comment]
O problema era que tava faltando popular o campo das entidades

![image](https://user-images.githubusercontent.com/54081877/127923294-ca1a9cc0-3614-4920-8025-777b94a9c6d5.png)

https://github.com/mia-ajuda/Backend/commit/c7e5759f7fdcd0aa801e246121597a9317a18f35
