### ISSUE TITLE
Mostrar data de criação da pedido e oferta

### ISSUE THREAD

**Issue by sudjoao** [mia-ajuda/Documentation#209]
### Descrição:
Ao abrir um pedido ou oferta de ajuda não aparece nenhum indicativo de quando aquela oferta foi criado, isso trás um problema pois as vezes é uma oferta ou pedido muito antigo e o usuário não vai saber.

### Critérios de aceitação:

- Deverá mostrar ou a data de criação ou há quanto tempo o pedido foi criado.

### Tarefas:

- [x] Verificar qual atributo guarda a data de criação da ajuda/oferta;
- [x] Utilizar esse atributo para mostrar a data de criação;
- [x] Atributo deve estar visivel tanto na oferta quanto no pedido.

**Comment by guibrbs** [comment]
Mergeado.
