### ISSUE TITLE
[V2] Notificações do Aplicativo

### ISSUE THREAD

**Issue by sudjoao** [mia-ajuda/Documentation#210]
**Descreva o bug**
Algumas notificações relacionadas aos pedidos de ajuda não estão notificando o celular do usuário. Além disso as notificações para campanhas e ofertas não estão funcionando.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Logar no aplicativo com uma conta A;
2. Criar um pedido / oferta;
3. Em outro celular logar com uma conta B;
4. Tentar oferecer ajuda / interagir com a oferta do usuário A;
5. É esperado que chegue uma notificação nativa no celular do usuário A porém isso nem sempre acontece para os pedidos e não acontece para as ofertas e campanhas.

**Comportamento esperado**
É esperado que o usuário receba notificações nos seguintes momentos:
1. Interações com pedidos
  - Alguém ofereça ajuda no seu pedido;
  - Quando ele escolher alguém para ajudá-lo esta pessoa deve receber uma notificação.
2. Interações com ofertas
  - Alguém peça ajuda na sua oferta;
  - Ao escolher uma pessoa para ajudar essa pessoa deve receber notificação.
3. Campanhas (ONG)
  - Alguém interaja com sua campanha (ONG);
  - A ONG interagir com a pessoa de volta.   

**Informações adicionais**
É possível que as notificações para campanhas e ofertas não tenham sido implementadas, neste caso verificar como as notificações do pedido foram feitas e seguir a mesma lógica.

**Comment by guibrbs** [comment]
As notificações foram testadas em ambiente de produção e estão todas funcionando de acordo, caso haja o interesse de validação lembre-se de fechar o Expo para validar a funcionalidade.
