### ISSUE TITLE
(ONG1) Cadastrar ONG

### ISSUE THREAD

**Issue by lxgustxl** [mia-ajuda/Documentation#217]
|  name | about |  title | labels | assignees |
| --------- | ---------- | --------- | --------- | ------------- |
| Criar uma nova ONG | Nova Funcionalidade| Cadastrar ONG | backend | [gustavomartins-github](https://github.com/gustavomartins-github) |

### Descrição: 

- Eu como representante de uma ONG, gostaria de cadastra-la para poder fornecer apoio aos necessitados

### Critérios de aceitação:

- o formulário deverá conter os campos necessários para se cadastrar uma ONG;

### Descrição da funcionalidade

- A funcionalidade deve receber os dados necessários do usuário e retornar 1 quando os dados recebidos estão corretos, caso contrário, se eventualmente algum input estiver errado (em relação ao domínio de entrada), deverá retorna 0.

### Tarefas:

- [x] Desenvolver uma função contendo um formulário para cadastrar ONGs;
- [x] Testar a função de cadastro de ONGs criada;

**Comment by guibrbs** [comment]
Agradeço a contribuição!
No entanto, no projeto Mia Ajuda nós já consideramos uma ONG como entidade, caracterizada por Entity na implementação. Portanto, como esta funcionalidade já está implementada e funcional no aplicativo, estaremos fechando a issue e o PR.
Qualquer dúvida ou comentário, sinta-se a vontade para comentar aqui na issue.
