### ISSUE TITLE
US22 - Ver Pedidos em Andamento

### ISSUE THREAD

**Issue by Eduardolimr** [mia-ajuda/Documentation#22]
### Descrição:
Eu, como usuário que pede ajuda, desejo ver em uma lista separada com os meus pedidos em andamento, para que possa diferencia-los dos demais

### Critérios de aceitação:
- [x] O usuário deve poder visualizar seus pedidos em andamento;
- [ ] O usuário deve poder selecionar um pedido em andamento;
- [x] Essa lista deve ser separada dos pedidos inativos;
- [ ] Funcionalidade testada.

### Tarefas:
- [x] Criar lista separada dos pedidos em aberto ou concluído;
- [ ] Testar lista ao atualizar estado do pedido;
- [ ] Testar funcionalidades;

**Comment by LeoSilvaGomes** [comment]
![image](https://user-images.githubusercontent.com/61520601/78717137-8660cc00-78f6-11ea-96bb-63ad65d8500a.png)
De acordo com o protótipo, ficamos com dúvida se devemos fazer tanto o pedido em andamento quantos os finalizados já que o nome da issue é ```ver pedidos em andamento```, enquanto nos critérios de aceitação temos ``` Essa lista deve ser separada dos pedidos inativos```.
Devemos fazer a todas as funcionalidades ou apenas a parte de pedidos em andamento?
