### ISSUE TITLE
Cálculo da distância das ajudas.

### ISSUE THREAD

**Issue by darmsDD** [mia-ajuda/Documentation#65]
### Descrição:
Atualmente a distância que é mostrada ao clicar numa ajuda no mapa, é em referência a última posição que o mapa teve que fazer uma requisição em vez da posição inicial do usuário. Como pode ser observado na foto mesmo a ajuda estando fora do círculo preto(que está transparente) que deveria indicar 2 km de raio a distância se mostra de 588m.
![photo5035034412605089911](https://user-images.githubusercontent.com/42387797/81842080-cc2a3900-9521-11ea-861d-8419ba9bfde5.jpg)

### Critérios de aceitação:
* A distância apresentada em uma ajuda deve ser em relação a posição do usuário(currentRegion).

### Tarefas:

- [ ] Alterar a requisição do backend para receber a posição atual do usuário.
- [ ] Alterar a requisição do front-end para mandar a posição atual do usuário.
- [ ] Alterar o socket para calcular a distância com base na posição atual do usuário.
- [ ] Calcular a distância entre o usuário e a ajuda com base nessa posição.

**Comment by darmsDD** [comment]
Porque esse issue foi fechada?

**Comment by LhTaira** [comment]
> Porque esse issue foi fechada?

Porque a distância foi retirada em algum pra que não mencionou essa issue

**Comment by darmsDD** [comment]
Esse pr envolve mais coisas, como a parte do socket. Atualmente só foi retirado as distâncias no mapa.
