### ISSUE TITLE
Mudança de filtro não afeta resultado

### ISSUE THREAD

**Issue by LhTaira** [mia-ajuda/Documentation#77]
**Descreva o bug**
Na página principal do app, com resultados já filtrados, se o usuário mudar o filtro, desmarcando as caixas marcadas e marcando outras e clicar em 'filtrar' os resultados aparecem sem filtro.

**Para reproduzir**
1. Vá para a página principal
2. Clique em no botão de filtro
3. marque qualquer categoria e clique em filtrar
4. Observe que os resultados foram filtrados como esperado
5. Clique no botão de filtro novamente
6. Desmarque o a categoria selecionada e marque outra e clique em filtrar
7. Observe que os resultados não estão filtrados

**Comportamento esperado**
Após mudar a categoria a ser filtrada os resultados viriam filtrados com base no novo parâmetro.

**Smartphone (por favor, informe qual é o navegador, browser utilizado ao encontrar o bug):**
 - Device: Emulador de android
 - OS: Android 10.0.0

**Comment by darmsDD** [comment]
Não consegui observar este erro, então fecharei a issue. Caso o erro seja observado essa issue deve ser reaberta.
