### ISSUE TITLE
M17 - Redirecionar para ajuda ao clicar na notificação

### ISSUE THREAD

**Issue by WelisonR** [mia-ajuda/Documentation#96]
### Descrição:

Como as notificações remetem a uma ajuda, ao clicar na notificação o usuário poderia ser direcionado diretamente para o pedido de ajuda para realizar alguma ação.

### Critérios de aceitação:

- [x] Redirecionar para a ajuda ao clicar na notificação.

### Tarefas:

- [x] Na aba notificações, redirecionar o usuário para a ajuda ao clicar na ajuda.
- [x] Nas notificações enviadas, redirecionar o usuário para a ajuda ao clicar na ajuda. (caso possível)

**Comment by AnaCarolcs** [comment]
@WelisonR , o que ficou resolvido dessa issue?

**Comment by WelisonR** [comment]
@AnaCarolcs A issue foi realizada pelo @sudjoao
