### ISSUE TITLE
Monitoramento de erros

### ISSUE THREAD

**Issue by GabrielDVpereira** [mia-ajuda/Documentation#99]
### Descrição:
Hoje, não temos nenhum monitoramento de erro estruturado que consiga capturar qualquer tipo de erro que acontece em produção. Por isso, devemos estruturar alguma solução para conseguir interceptar qualquer erro que possa acorrer.

### Critérios de aceitação:

- Ser capaz de inteceptar qualquer erro para consulta posterior do mesmo em algum lugar.

### Tarefas:

- [x] Estruturar um ambiente de monitoramento. 
- [x] analizar se o monitoramento está interceptando os erros que acontecem em produção.

### Observações:

- Algumas soluções envolvem sistemas já prontos para tal. Como [sentry](https://sentry.io/welcome/?utm_source=google&gclid=Cj0KCQjwirz3BRD_ARIsAImf7LPVMbTxO7-JiOau8CA2j6ieOxmZ7LGzqhUDN7UooRvbMx9B5022XK0aAtRKEALw_wcB) ou [bugsnag](https://www.bugsnag.com/)

- Uma solução sem depender de terceiros consiste em usar nossa própria base no mongo. É possível criar uma tabela "monitoramento" e salvar dados do erro como rota, usuário, mensagem do erro, data, hora e etc toda vez que alguma rota lançar uma excessão.

**Comment by Phe0** [comment]
https://cloud.google.com/logging/docs/setup/nodejs?hl=pt-br
